name: Deploy Docker Image dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    uses: Ocean-Science-Analytics/.github/.github/workflows/k8s-docker-build-cicd.yaml@v1.0.0
    with:
      image_name: "apps/pamportal"
      dockerfile_path: "Dockerfile"
      environment: "dev"