name: Deploy Docker Image prod

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    uses: Ocean-Science-Analytics/.github/.github/workflows/k8s-docker-build-cicd.yaml@1.0.0
    with:
      image_name: "k8s-apps/pamportal"
      dockerfile_path: "Dockerfile"
      environment: "prod"
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}